{% set version = "0.9.22" %}

package:
  name: lmdb
  version: {{ version }}

source:
  url: https://github.com/LMDB/lmdb/archive/refs/tags/LMDB_{{ version }}.tar.gz
  sha256: f3927859882eb608868c8c31586bb7eb84562a40a6bf5cc3e13b6b564641ea28
  patches:
    - patches/Makefile.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("lmdb", max_pin="x.x.x") }}

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - cmake  # [win]
    - ninja  # [win]

test:
  requires:
    # CMake needs compiler on Windows to be able to run package detection.
    # See: https://discourse.cmake.org/t/questions-about-find-package-cli-msvc/6194
    - {{ compiler('cxx') }}  # [win]
    - cmake                  # [win]
  files:
    - cmake_test/

  commands:
    # binaries
    - mdb_copy -V  # [unix]
    - mdb_dump -V  # [unix]
    - mdb_load -V  # [unix]
    - mdb_stat -V  # [unix]

    # presence of shared lib:
    - test -f ${PREFIX}/lib/liblmdb.so               # [unix]
    - if not exist %LIBRARY_BIN%\lmdb.dll exit 1     # [win]
    - if not exist %LIBRARY_LIB%\lmdb.lib exit 1     # [win]

    # absence of static lib:
    - test ! -f ${PREFIX}/lib/liblmdb.a              # [unix]

    # headers:
    - test -f ${PREFIX}/include/lmdb.h               # [unix]
    - if not exist %LIBRARY_INC%\lmdb.h exit 1       # [win]

    # Test CMake installation on Windows
    - cd cmake_test                                  # [win]
    - cmake %CMAKE_ARGS% .                           # [win]

about:
  home: https://www.openldap.org/software/repo.html
  license: OLDAP-2.8
  license_file: libraries/liblmdb/LICENSE
  summary: A high-performance embedded transactional key-value store database.
  # this is a mirror; the original sources come from gitlab, see
  # https://git.openldap.org/openldap/openldap/-/tree/mdb.master
  dev_url: https://github.com/LMDB/lmdb

extra:
  recipe-maintainers:
    - jakirkham
    - h-vetinari
    - jjerphan
