{% set version = "0.9.29" %}

package:
  name: lmdb
  version: {{ version }}

source:
  url: https://github.com/LMDB/lmdb/archive/refs/tags/LMDB_{{ version }}.tar.gz
  sha256: 22054926b426c66d8f2bc22071365df6e35f3aacf19ad943bc6167d4cae3bebb
  patches:
    - patches/Makefile.patch

build:
  number: 1

requirements:
  build:
    - make
    - {{ compiler('c') }}

test:
  commands:
    # binaries
    - mdb_copy -V
    - mdb_dump -V
    - mdb_load -V
    - mdb_stat -V

    # presence of shared lib:
    - test -f ${PREFIX}/lib/liblmdb.so

    # absence of static lib:
    - test ! -f ${PREFIX}/lib/liblmdb.a

    # headers:
    - test -f ${PREFIX}/include/lmdb.h

about:
  home: https://www.openldap.org/software/repo.html
  license: OLDAP-2.8
  license_file: libraries/liblmdb/LICENSE
  summary: A high-performance embedded transactional key-value store database.
  # this is a mirror; the original sources come from gitlab, see
  # https://git.openldap.org/openldap/openldap/-/tree/mdb.master
  dev_url: https://github.com/LMDB/lmdb

extra:
  recipe-maintainers:
    - jakirkham
    - h-vetinari
