{% set version = "0.9.29" %}
{% set sha256 = "22054926b426c66d8f2bc22071365df6e35f3aacf19ad943bc6167d4cae3bebb" %}
{% set build = 0 %}

package:
  name: lmdb
  version: {{ version }}

source:
  fn: LMDB_{{ version }}.tar.gz
  url: https://github.com/LMDB/lmdb/archive/LMDB_{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - Makefile.patch

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - make
    - {{ compiler('c') }}

test:
  commands:
    - mdb_copy -V                                    # [unix]
    - mdb_dump -V                                    # [unix]
    - mdb_load -V                                    # [unix]
    - mdb_stat -V                                    # [unix]
    - test -f ${PREFIX}/lib/liblmdb.a                # [unix]
    - test -f ${PREFIX}/lib/liblmdb.so               # [unix]

about:
  home: http://symas.com/mdb/
  license: OpenLDAP Public
  license_file: libraries/liblmdb/LICENSE
  summary: A high-performance embedded transactional key-value store database.

extra:
  recipe-maintainers:
    - jakirkham
