{% set version = "0.9.28" %}

package:
  name: lmdb
  version: {{ version }}

source:
  url: https://github.com/LMDB/lmdb/archive/refs/tags/LMDB_{{ version }}.tar.gz
  sha256: 47457d3d3ae2c489b52078a07e9f55ec6e094b48c2204029c7754e2972fe1882
  patches:
    - patches/Makefile.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - make
    - {{ compiler('c') }}

test:
  commands:
    # binaries
    - mdb_copy -V
    - mdb_dump -V
    - mdb_load -V
    - mdb_stat -V

    # presence of shared lib:
    - test -f ${PREFIX}/lib/liblmdb.so

    # absence of static lib:
    - test ! -f ${PREFIX}/lib/liblmdb.a

    # headers:
    - test -f ${PREFIX}/include/lmdb.h

about:
  home: https://www.openldap.org/software/repo.html
  license: OLDAP-2.8
  license_file: libraries/liblmdb/LICENSE
  summary: A high-performance embedded transactional key-value store database.
  # this is a mirror; the original sources come from gitlab, see
  # https://git.openldap.org/openldap/openldap/-/tree/mdb.master
  dev_url: https://github.com/LMDB/lmdb

extra:
  recipe-maintainers:
    - jakirkham
    - h-vetinari
