{% set version = "0.9.24" %}

package:
  name: lmdb
  version: {{ version }}

source:
  url: https://github.com/LMDB/lmdb/archive/LMDB_{{ version }}.tar.gz
  sha256: 44602436c52c29d4f301f55f6fd8115f945469b868348e3cddaf91ab2473ea26
  patches:
    - Makefile.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - make
    - {{ compiler('c') }}

test:
  commands:
    - mdb_copy -V                                    # [unix]
    - mdb_dump -V                                    # [unix]
    - mdb_load -V                                    # [unix]
    - mdb_stat -V                                    # [unix]
    - test -f ${PREFIX}/lib/liblmdb.a                # [unix]
    - test -f ${PREFIX}/lib/liblmdb.so               # [unix]

about:
  home: https://www.openldap.org/software/repo.html
  license: OLDAP-2.8
  license_file: libraries/liblmdb/LICENSE
  summary: A high-performance embedded transactional key-value store database.
  # careful: the gitlab repo has different branches for very
  # different projects - relevant here are the ones called mdb.*;
  # also: there's a mirror under https://github.com/LMDB/lmdb
  dev_url: https://git.openldap.org/openldap/openldap/-/tree/mdb.master

extra:
  recipe-maintainers:
    - jakirkham
