travis:
  secure:
    BINSTAR_TOKEN: NsbOoLGSEuUziVKto/S4Bpq+3E8M8EteiaMjQh5n/5Ia0+BwDlD2mHcOEJyRet1qsiK+T+ni39Iw5Ibeot/vn6/sNs8WKwCXKgXH28982bZqQe+jPEwig81OVBT+YMLE/MIY/qQQno0RAgbOrLAhgv0E1puG7UIwMNZ2HAwtTO7ksJA7R6iNK3CBlo6hPkEd/Al2hq8sWPoIpree4+bN1vC6t+HRhoQvU4lJsw7FqhtTLd1mTS+gRpOSbjvpUuskRDrO74ctlOY1vVLADYeQF4+qRKsJ8hbbO9j8nx2M07zj+T2iKkyF7OhIva+lXpO6H6x454adg1WOlaaY4MPs0mkO8vPRSTlagby3LCFi0MPudZ89oz3tklxUCpz1FLliGY77PjldzIbdV5VAQL3mvi/gJsmWx4yBaJXjnVh+9AQRt+e+PSxuF/0H5xlBL3z6EWIErvDqDL3YLYsG4sGth6mN6WM2Dpm9APs+lNJGUS5D/Se4nKjX3LGugIt7loTctBPFuvf1TXQWzp5kjxSGHpFEKBtFdcjCBNvDBqcJxyajlCFkkzYPHTyWkFozDnzMHIdjKO+rUQ8DDi4+yboAVVFv/ATPIgtgt5oFKsq8kb7xsRe0dGyKG/7VNZiaWQAzZHbIf161R4moQNhzKc+GlSWn8vVZ8pITaX06n6U3was=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
