--- libraries/liblmdb/Makefile
+++ libraries/liblmdb/Makefile
@@ -27,7 +27,7 @@
 LDLIBS	=
 SOLIBS	=
 SOEXT	= .so
-prefix	= /usr/local
+prefix	=
 exec_prefix = $(prefix)
 bindir = $(exec_prefix)/bin
 libdir = $(exec_prefix)/lib
